# Generated by Django 5.2.12 on 2026-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='temperature',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='stage',
            field=models.CharField(default='IDLE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='stitch_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
