# Generated by Django 5.2.12 on 2026-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_remove_sensorreading_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='ecur_var',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='evib_var',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='pattern_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='run_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='spm',
            field=models.IntegerField(default=0),
        ),
    ]
